<a href="https://colab.research.google.com/github/Dev1561/090_DevParmar/blob/main/090_Lab1_LinearAlgebraWithNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import numpy as np
matrix3x2 = np.array([[1, 2], [3, 4], [5, 6]])
matrix2x3 = np.array([[1, 2, 4], [4, 5, 6]])

print('3 x 2 matrix : \n', matrix3x2)
print('\n 2 x 3 matrix : \n', matrix2x3)

3 x 2 matrix : 
 [[1 2]
 [3 4]
 [5 6]]

 2 x 3 matrix : 
 [[1 2 4]
 [4 5 6]]


In [3]:
random_matrix = np.random.rand(3, 4)
print(random_matrix)

[[0.60834742 0.64048931 0.89248323 0.28122704]
 [0.90921388 0.98021296 0.40547882 0.06306266]
 [0.17029303 0.42867573 0.03629416 0.77591414]]


In [4]:
# matrix multiplication
matmul = np.dot(matrix3x2, matrix2x3)
print(matmul)

[[ 9 12 16]
 [19 26 36]
 [29 40 56]]


In [ ]:
# elemet wise matrix multiplication
