<a href="https://colab.research.google.com/github/Dev1561/090_DevParmar/blob/main/Lab1/090_Lab1_LinearAlgebraWithNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import numpy as np
matrix3x2 = np.array([[1, 2], [3, 4], [5, 6]])
matrix2x3 = np.array([[1, 2, 4], [4, 5, 6]])

print('3 x 2 matrix : \n', matrix3x2)
print('\n 2 x 3 matrix : \n', matrix2x3)

3 x 2 matrix : 
 [[1 2]
 [3 4]
 [5 6]]

 2 x 3 matrix : 
 [[1 2 4]
 [4 5 6]]


In [ ]:
matmul = matrix3x2 * matrix2x3
print('Matrix multiplication : \n', matmul)

SyntaxError: ignored