<a href="https://colab.research.google.com/github/Dev1561/090_DevParmar/blob/main/Lab4/090_Lab4_ClassifyingDigits.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


Task 2: Apply algorithm on digits dataset - LabelEncoding of features: and Train test Division 80%-20%

---



In [2]:
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
import pandas as pd
import numpy as np

#loading dataset
digits = datasets.load_digits()
print(digits)

{'data': array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]]), 'target': array([0, 1, 2, ..., 8, 9, 8]), 'target_names': array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), 'images': array([[[ 0.,  0.,  5., ...,  1.,  0.,  0.],
        [ 0.,  0., 13., ..., 15.,  5.,  0.],
        [ 0.,  3., 15., ..., 11.,  8.,  0.],
        ...,
        [ 0.,  4., 11., ..., 12.,  7.,  0.],
        [ 0.,  2., 14., ..., 12.,  0.,  0.],
        [ 0.,  0.,  6., ...,  0.,  0.,  0.]],

       [[ 0.,  0.,  0., ...,  5.,  0.,  0.],
        [ 0.,  0.,  0., ...,  9.,  0.,  0.],
        [ 0.,  0.,  3., ...,  6.,  0.,  0.],
        ...,
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  1., ...,  6.,  0.,  0.],
        [ 0.,  0.,  0., ..., 10.,  0.,  0.]],

       [[ 0.,  0.,  0., ..., 12.,  0

In [3]:
print(digits.data.shape)
print(digits.target.shape)

(1797, 64)
(1797,)


In [4]:
from sklearn.model_selection import train_test_split

x = digits.data
y = digits.target

#splitting data into train and test sets
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.20, random_state = 90)

#creating a decision tree classifier using gini
classifier = DecisionTreeClassifier(criterion = 'gini', random_state = 90, max_depth = 7, min_samples_leaf = 26)
classifier.fit(x_train, y_train)

#predicting classes of test data
y_pred = classifier.predict(x_test)
print('Predicted values  :  \n')
print(y_pred)

Predicted values  :  

[2 1 5 3 1 1 4 7 3 7 4 0 9 4 7 8 9 1 7 0 2 8 0 4 4 0 4 9 9 6 0 8 2 4 8 4 9
 7 5 0 5 9 1 9 7 1 9 1 0 9 7 1 2 0 2 2 8 4 1 6 8 8 1 4 6 7 0 0 1 9 3 2 2 6
 0 9 7 7 5 0 6 2 8 1 1 1 1 1 8 5 8 1 9 2 1 0 1 8 1 7 6 8 9 9 5 6 9 0 3 9 9
 7 8 7 0 0 0 8 5 0 7 6 6 3 3 4 4 1 2 5 8 6 9 8 5 8 5 6 5 3 4 6 5 7 1 6 4 1
 0 1 0 6 7 4 4 5 5 9 5 1 0 7 1 5 6 0 1 6 1 4 4 9 7 6 6 3 5 6 7 8 8 5 5 0 1
 0 2 8 1 4 3 7 4 4 4 8 3 9 6 0 8 1 9 4 9 6 2 2 1 4 2 8 1 8 1 4 3 2 5 6 6 8
 8 6 2 4 0 4 8 4 5 5 1 6 5 0 8 3 3 6 4 7 0 2 1 9 8 4 1 7 6 2 7 6 6 4 7 0 8
 5 7 8 8 0 1 7 9 0 3 7 4 1 7 7 7 1 2 6 0 7 5 4 3 5 2 0 1 1 3 2 1 1 6 6 4 7
 9 2 8 1 3 7 5 3 6 7 2 1 5 1 9 5 8 1 5 1 1 2 6 5 9 1 2 6 1 7 6 9 4 5 1 3 6
 5 4 6 1 8 3 2 8 4 7 4 1 9 7 2 8 3 5 7 8 1 9 6 6 1 0 4]


In [5]:
#model accuracy
from sklearn import metrics
print('Confusion Matrix :  \n', metrics.confusion_matrix(y_test, y_pred))
print('\nAccuracy :  ', metrics.accuracy_score(y_test, y_pred))
print('\nReport :  ', metrics.classification_report(y_test, y_pred))

Confusion Matrix :  
 [[33  1  0  0  0  0  0  1  0  1]
 [ 0 34  1  0  4  0  0  0  3  0]
 [ 0  3 20  1  1  0  3  4  1  0]
 [ 0  2  4 18  0  0  0  1  2  2]
 [ 0  5  0  0 30  1  0  3  0  0]
 [ 0  1  1  1  2 30  0  0  0  1]
 [ 1  4  0  0  1  0 37  0  1  0]
 [ 0  2  0  0  1  0  0 27  4  0]
 [ 0  2  0  0  0  0  0  0 26  0]
 [ 0  3  2  1  0  3  0  2  1 27]]

Accuracy :   0.7833333333333333

Report :                 precision    recall  f1-score   support

           0       0.97      0.92      0.94        36
           1       0.60      0.81      0.69        42
           2       0.71      0.61      0.66        33
           3       0.86      0.62      0.72        29
           4       0.77      0.77      0.77        39
           5       0.88      0.83      0.86        36
           6       0.93      0.84      0.88        44
           7       0.71      0.79      0.75        34
           8       0.68      0.93      0.79        28
           9       0.87      0.69      0.77        39

    ac